name: Build
on:
  #push:
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: Install Node Dependencies
        run: |
          npm install
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipreqs
          python -m  pipreqs.pipreqs --encoding utf-8  ./ --force
          pip install -r requirements.txt
      - name: Install Extras
        run: |
          sudo apt-get update
      - name: Run Script
        run: |
          rm -rf node_modules package-lock.json
          npm install
          node main.js
      - name: Force add, commit, and push all changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Auto-commit all changes" || echo "Nothing to commit"
          git pull --strategy=ours origin ${{ github.ref_name }} --allow-unrelated-histories || true
          git push origin HEAD:${{ github.ref_name }} --force